language: python
python:
  - 2.7
  - 3.4
  - 3.5

install:
#  - pip install prov rdflib graphviz pydotplus pydot pytest
   - python setup.py install
   - apt-get install graphviz

script:
#   - python nidm/experiment/tests/test_experiment.py
  - py.test -v